// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpxijrkokwnigoddtpqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdweGlqcmtva3duaWdvZGR0cHF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYyNjU0NTIsImV4cCI6MjA2MTg0MTQ1Mn0.AwERC9Ne1XH-9lql_qSJR2XV_KxfODbnD7EzaIgjbf0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);